name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: |
          make -j releases
          cd bin && sha256sum * > checksums.txt && cd ..
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
